### ISSUE TITLE
http timeout crash

### ISSUE THREAD

**Issue by codefisher** [torchbox/django-recaptcha#56]
Django emailed me the bellow error yesterday.  It looks like you need to add a try/except in there for when the request times out.

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "./djangopress/forum/views.py", line 113, in new_thead
    if thread_form.is_valid() and post_form.is_valid():
  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 162, in is_valid
    return self.is_bound and not bool(self.errors)
  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 154, in errors
    self.full_clean()
  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 353, in full_clean
    self._clean_fields()
  File "/usr/local/lib/python2.7/site-packages/django/forms/forms.py", line 368, in _clean_fields
    value = field.clean(value)
  File "/usr/local/lib/python2.7/site-packages/captcha/fields.py", line 68, in clean
    remoteip=self.get_remote_ip(), use_ssl=self.use_ssl)
  File "/usr/local/lib/python2.7/site-packages/captcha/client.py", line 123, in submit
    httpresp = urlopen(req)
  File "/usr/local/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/local/lib/python2.7/urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "/usr/local/lib/python2.7/httplib.py", line 1067, in getresponse
    response.begin()
  File "/usr/local/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python2.7/httplib.py", line 365, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/local/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

**Comment by thibaudcolas** [comment]
I’ll assume this was a one-off since we only received the one report – closing.
